### ISSUE TITLE
Manually trigger tests on initial page load

### ISSUE THREAD

**Issue by ghost** [harvesthq/harvey#10]
It seems like the tests only trigger on orientation change or when you start resizing. How can I do an initial state check after I attach tests? It would seem important to know the state on page load, eh?

I tried Harvey._update_states() after Harvey.attach but I get an error:

Uncaught TypeError: Cannot read property 'length' of undefined Line 94

Assuming I'm calling _update_states too soon?

**Comment by jkintscher** [comment]
Whenever you `attach()` a media query Harvey [automatically checks](https://github.com/harvesthq/harvey/blob/master/harvey.coffee#L36) whether it's currently valid or not and will call its `setup` and `on` callbacks if appropriate. You shouldn't need to do any manually there. In what context are you attaching those media queries?

BTW, calling the internal [`Harvey._update_states()`](https://github.com/harvesthq/harvey/blob/master/harvey.coffee#L71) without parameters will definitely throw a `TypeError` as it expects a list of states and a boolean switch to either active or deactivate those states.

**Comment by ghost** [comment]
Thanks for the clarification, it is working as expected. My screen was set to a width where no Harvey tests applied on page load.
