### ISSUE TITLE
Major IE Issue

### ISSUE THREAD

**Issue by quantizor** [harvesthq/harvey#6]
addListener is not supported in IE, so this plugin doesn't work and will break other JS on the page.

**Comment by quantizor** [comment]
Here's the error thrown in IE9:

SCRIPT438: Object doesn't support property or method 'addListener' 
harvey.js, line 1 character 790

I minified it with YUI2, but you get the idea.

**Comment by quantizor** [comment]
So I figured it out eventually... weird collision with Respond.JS - might be worth looking into.

**Comment by jkintscher** [comment]
Thanks for pointing this out! add(Event)Listener should not cause problems in IE (as it defaults to the supported attachEvent) but any possible compatibility issue with Respond.JS will definitely be investigated! Sorry it didn't work for you straight away.

Please open a new issue/pull request if you are able to find anything helpful!
