### ISSUE TITLE
IE8 Console Error

### ISSUE THREAD

**Issue by quantizor** [harvesthq/harvey#7]
Getting this on your demo site too..

SCRIPT65535: Unexpected call to method or property access. 
harvey.js, line 159 character 7

Looks like it's referencing this code block:

``` javascript
Harvey._add_css_for = function(mediaQuery) {
    if (!this.style) {
        this.style = document.createElement('style');
        document.getElementsByTagName('head')[0].appendChild(this.style);
    }
    return this.style.appendChild(document.createTextNode("@media " + mediaQuery + " {.harvey-test{}}"));
};
```

Specifically the return call.

**Comment by jkintscher** [comment]
Thanks for reporting this! The error should no longer be appear as of https://github.com/harvesthq/harvey/commit/3d2e095bb78ce7723dc620df6a9d4c2322c6f41f

This, of course, still adds no media query support for IE < 9 :)
Let me know if this fixes it for you.

**Comment by quantizor** [comment]
Looks to have fixed it, thanks!
