### ISSUE TITLE
support for respond.js

### ISSUE THREAD

**Issue by geertbrit** [harvesthq/harvey#9]
looks like a great plugin, but one big thing that seems to be missing: 
support for legacy browsers using respond.js as polyfill. 

It seems some issues already talk about Respond.js, but it just doesn't seem to work. 

I.e: media-queries 'fired' by Respond.js don't appear to be tracked in Harvey.  Is this on the roadmap?
Thanks

**Comment by jkintscher** [comment]
Harvey already attempts to offer the widest support possible by applying several of polyfills and patches behind the scenes. Of course this does not work for every browser (especially IE is picky) but it already achieves widespread support.

Direct integration of `Respond.js` is not planned so far as it would introduce dependencies which this project tries to avoid entirely.

Still, that being said it shouldn't be the biggest deal to have a small bridging script built on top of `Harvey` to make it listen/attach to media queries from `Response.js`. I'll probably not get to look into this in the nearest future, though if you'd like to build something like that I'd be more than glad to add it here.
